# Generated by Django 5.1.6 on 2025-02-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ANULAR', 'Anulación')], max_length=10)),
                ('tabla', models.CharField(max_length=20)),
                ('registro_id', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField()),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
