# Generated by Django 5.1.6 on 2025-02-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('registro_tipo', models.CharField(max_length=20)),
                ('registro_id', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
