# Generated by Django 5.1.6 on 2025-03-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinarios', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ordinario',
            index=models.Index(fields=['numero', 'creada'], name='ordinarios__numero_0c0105_idx'),
        ),
    ]
