# Generated by Django 5.1.6 on 2025-02-27 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='# Memorando')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('iddoc', models.PositiveIntegerField(verbose_name='IDDOC')),
                ('destinatario', models.CharField(max_length=100, verbose_name='Destinatario')),
                ('materia', models.TextField(max_length=5000, verbose_name='Materia')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
    ]
