# Generated by Django 5.1.6 on 2025-02-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Nº Ordinario')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('iddoc', models.PositiveIntegerField(verbose_name='IDDOC')),
                ('destinatario', models.CharField(blank=True, max_length=100)),
                ('materia', models.TextField(max_length=5000)),
                ('autor', models.CharField(max_length=10)),
                ('anulada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
    ]
