# Generated by Django 5.1.6 on 2025-03-06 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Nº Memorando')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('iddoc', models.PositiveIntegerField(blank=True, null=True, verbose_name='IDDOC')),
                ('destinatario', models.CharField(blank=True, max_length=100)),
                ('materia', models.TextField(max_length=5000)),
                ('autor', models.CharField(max_length=10)),
                ('anulada', models.BooleanField(default=False)),
                ('redom', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='MemorandoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloqueado', models.BooleanField(default=False)),
                ('bloqueado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Libro de Memorandos',
                'verbose_name_plural': 'Configuraciones del Libro de Memorandos',
            },
        ),
    ]
