# Generated by Django 5.1.6 on 2025-02-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorandos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorando',
            name='numero',
            field=models.PositiveIntegerField(unique=True, verbose_name='Nº Memorando'),
        ),
    ]
