# Generated by Django 5.1.6 on 2025-03-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en las listas de selección')),
                ('es_municipio', models.BooleanField(default=True, help_text="Indica si el destinatario pertenece a 'Dentro del Municipio' (True) o 'Fuera del Municipio' (False)")),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
