# Generated by Django 5.1.6 on 2025-03-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinatarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinatario',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='destinatario',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de aparición en las listas de selección'),
        ),
    ]
