# Generated by Django 5.1.6 on 2025-03-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinatarios', '0002_alter_destinatario_options_destinatario_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='es_municipio',
            field=models.BooleanField(default=True, help_text="Indica si el destinatario pertenece a 'Dentro del Municipio' (True) o 'Fuera del Municipio' (False)"),
        ),
    ]
